package main

import (
	"flag"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
)

const (
	selfModule  = "github.com/DrewCyber/ydn64"
	scanPackage = "./cmd/ydn64"
	targetGOOS  = "linux darwin windows"
	preamble    = `ydn64 third-party licence notices
=================================

This file lists the licences of the third-party Go modules compiled into the
ydn64 binary. The ydn64 source code itself is licensed under the BSD Zero
Clause Licence (see the accompanying LICENSE file); everything below applies
only to the bundled third-party components.

Generated by "go run ./tools/licenses" — do not edit by hand.
`
)

type moduleInfo struct {
	path    string
	version string
	dir     string
	files   []string
}

func main() {
	out := flag.String("o", "THIRD-PARTY-NOTICES.txt", "output file")
	flag.Parse()

	modules := map[string]bool{}
	for _, goos := range strings.Fields(targetGOOS) {
		for _, m := range listModules(goos) {
			if m != "" && m != selfModule {
				modules[m] = true
			}
		}
	}
	names := make([]string, 0, len(modules))
	for m := range modules {
		names = append(names, m)
	}
	sort.Strings(names)

	var b strings.Builder
	b.WriteString(preamble)
	missing := false
	for _, name := range names {
		info, err := inspectModule(name)
		if err != nil {
			die("inspecting %s: %v", name, err)
		}
		fmt.Fprintf(&b, "\n%s\nModule:  %s\nVersion: %s\nSource:  https://%s\n", strings.Repeat("=", 78), info.path, info.version, info.path)
		if len(info.files) == 0 {
			missing = true
			b.WriteString("Licence: !! NO LICENCE FILE FOUND IN MODULE !!\n")
			continue
		}
		fmt.Fprintf(&b, "Licence files: %s\n%s\n", strings.Join(baseNames(info.files), ", "), strings.Repeat("-", 78))
		for _, f := range info.files {
			data, err := os.ReadFile(f)
			if err != nil {
				missing = true
				fmt.Fprintf(&b, "[unreadable: %v]\n", err)
				continue
			}
			b.Write(data)
			if len(data) > 0 && data[len(data)-1] != '\n' {
				b.WriteString("\n")
			}
		}
	}

	if dir := filepath.Dir(*out); dir != "." {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			die("creating output directory: %v", err)
		}
	}
	if err := os.WriteFile(*out, []byte(b.String()), 0o644); err != nil {
		die("writing %s: %v", *out, err)
	}
	fmt.Printf("wrote %s (%d modules)\n", *out, len(names))
	if missing {
		os.Exit(1)
	}
}

func listModules(goos string) []string {
	tmpl := "{{if not .Standard}}{{with .Module}}{{.Path}}{{end}}{{end}}"
	cmd := exec.Command("go", "list", "-deps", "-f", tmpl, scanPackage)
	cmd.Env = append(os.Environ(), "GOOS="+goos, "CGO_ENABLED=0")
	out, err := cmd.Output()
	if err != nil {
		die("go list -deps (GOOS=%s): %v", goos, err)
	}
	return strings.Fields(string(out))
}

func inspectModule(name string) (*moduleInfo, error) {
	cmd := exec.Command("go", "list", "-m", "-f", "{{.Dir}}\t{{.Version}}", "--", name)
	out, err := cmd.Output()
	if err != nil {
		return nil, err
	}
	parts := strings.SplitN(strings.TrimSpace(string(out)), "\t", 2)
	info := &moduleInfo{path: name, version: parts[len(parts)-1]}
	if parts[0] != "" {
		info.dir = parts[0]
	}
	if info.dir == "" {
		return info, nil
	}
	entries, err := os.ReadDir(info.dir)
	if err != nil {
		return info, nil
	}
	candidates := []string{"LICENSE", "COPYING", "COPYRIGHT", "NOTICE", "PATENTS"}
	for _, base := range candidates {
		for _, e := range entries {
			n := e.Name()
			if e.IsDir() || !strings.HasPrefix(n, base) || containsStr(info.files, n) {
				continue
			}
			if n != base && !isLicenseFileExt(strings.TrimPrefix(n, base)) {
				continue
			}
			info.files = append(info.files, filepath.Join(info.dir, n))
		}
	}
	return info, nil
}

func baseNames(paths []string) []string {
	names := make([]string, len(paths))
	for i, p := range paths {
		names[i] = filepath.Base(p)
	}
	return names
}

func isLicenseFileExt(ext string) bool {
	switch strings.ToLower(ext) {
	case "", ".md", ".txt", ".html":
		return true
	default:
		return false
	}
}

func containsStr(list []string, s string) bool {
	for _, v := range list {
		if v == s {
			return true
		}
	}
	return false
}

func die(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "licenses: "+format+"\n", args...)
	os.Exit(2)
}
