package config

import (
	"crypto/ed25519"
	"fmt"
	"net"
	"os"
	"path/filepath"
	"strings"

	"github.com/hjson/hjson-go/v4"
	"github.com/yggdrasil-network/yggdrasil-go/src/address"
	ygconfig "github.com/yggdrasil-network/yggdrasil-go/src/config"
)

// Generate creates yggdrasil.conf and ydn64.toml in outDir with
// a freshly generated key pair and pre-derived pool6 address.
func Generate(outDir string) error {
	if err := os.MkdirAll(outDir, 0755); err != nil {
		return fmt.Errorf("creating output directory: %w", err)
	}

	// Generate a fresh yggdrasil NodeConfig (includes a new random key pair).
	ygCfg := ygconfig.GenerateConfig()
	// Force TUN-less operation and no admin socket.
	ygCfg.AdminListen = "none"
	ygCfg.IfName = "none"

	// Derive node address and pool6 subnet from the generated private key.
	privKey := ed25519.PrivateKey(ygCfg.PrivateKey)
	pubKey := privKey.Public().(ed25519.PublicKey)

	nodeAddr := address.AddrForKey(pubKey) // *address.Address = *[16]byte
	nodeIP := net.IP(nodeAddr[:])

	// address.Subnet is [8]byte — the /64 prefix bytes for this node's subnet.
	subnet := address.SubnetForKey(pubKey) // *address.Subnet = *[8]byte

	// Build the /96 pool6 prefix: 8 subnet bytes + 8 zero bytes → /96 subnet.
	pool6IP := make(net.IP, net.IPv6len) // 16 zero bytes
	copy(pool6IP, subnet[:])             // first 8 bytes from subnet prefix
	pool6CIDR := fmt.Sprintf("%s/96", pool6IP.String())
	pool6Prefix := pool6IP.String() // e.g. "301:363a:9499:c858::"

	// Write yggdrasil.conf (HJSON).
	ygBytes, err := hjson.Marshal(ygCfg)
	if err != nil {
		return fmt.Errorf("marshalling yggdrasil config: %w", err)
	}
	ygPath := filepath.Join(outDir, "yggdrasil.conf")
	if err := os.WriteFile(ygPath, ygBytes, 0600); err != nil {
		return fmt.Errorf("writing %s: %w", ygPath, err)
	}

	// Write ydn64.toml.
	tomlContent := buildTOML(nodeIP.String(), pool6CIDR, pool6Prefix)
	tomlPath := filepath.Join(outDir, "ydn64.toml")
	if err := os.WriteFile(tomlPath, []byte(tomlContent), 0600); err != nil {
		return fmt.Errorf("writing %s: %w", tomlPath, err)
	}

	fmt.Printf("Generated %s\n", ygPath)
	fmt.Printf("Generated %s\n", tomlPath)
	fmt.Printf("\nNode address : %s\n", nodeIP.String())
	fmt.Printf("NAT64 pool6  : %s\n", pool6CIDR)
	fmt.Printf("\nEdit yggdrasil.conf to add Peers, then start with:\n")
	fmt.Printf("  ydn64 -useconffile %s\n", tomlPath)
	return nil
}

func buildTOML(nodeIP, pool6CIDR, pool6Prefix string) string {
	var sb strings.Builder

	sb.WriteString("# ydn64 — TUN-less Yggdrasil node with NAT64 + DNS64\n")
	sb.WriteString("# Generated by: ydn64 -genconf\n\n")

	sb.WriteString("# Path to the yggdrasil HJSON config file.\n")
	sb.WriteString(`yggdrasil_conf = "./yggdrasil.conf"` + "\n\n")

	sb.WriteString("# Shared allowed source filter for both NAT64 and DNS64 services.\n")
	sb.WriteString("# CIDR notation or individual IPv6 addresses.\n")
	sb.WriteString(`allowed_sources = ["200::/7"]` + "\n\n")

	sb.WriteString("[nat64]\n")
	sb.WriteString("enable = true\n")
	sb.WriteString(fmt.Sprintf("pool6 = %q\n", pool6CIDR))
	sb.WriteString("# Idle timeout in seconds before a UDP NAT64 session is expired.\n")
	sb.WriteString("udp_timeout = 30\n\n")

	sb.WriteString("[dns64]\n")
	sb.WriteString("enable = false\n")
	sb.WriteString(fmt.Sprintf("listen = %q\n", "["+nodeIP+"]:53"))
	sb.WriteString(`default = "8.8.8.8:53"` + "\n")
	sb.WriteString("cache_expiration = 300\n")
	sb.WriteString("cache_purge = 600\n")
	sb.WriteString(`# invalid_address: "ignore" | "process" | "discard"` + "\n")
	sb.WriteString(`invalid_address = "ignore"` + "\n\n")

	sb.WriteString("# Default zone: synthesise AAAA records from A records using the NAT64 prefix.\n")
	sb.WriteString("[dns64.zones.default]\n")
	sb.WriteString(`domains = ["."]` + "\n")
	sb.WriteString("return-public-ipv4 = false\n")
	sb.WriteString(fmt.Sprintf("prefix = %q\n\n", pool6Prefix))

	sb.WriteString("# Example: Yggdrasil-native .ygg zone — forward to Alfis DNS, pass through 200::/7 responses.\n")
	sb.WriteString("# [dns64.zones.ygg]\n")
	sb.WriteString(`# domains = [".ygg"]` + "\n")
	sb.WriteString(`# forwarder = "[308:84:68:55::]:53"` + "\n\n")

	sb.WriteString("# Example: Pass-through zone — return real IPv4 and IPv6 records unchanged.\n")
	sb.WriteString("# [dns64.zones.passthrough]\n")
	sb.WriteString(`# domains = ["example.com", "com.tr"]` + "\n")
	sb.WriteString("# return-public-ipv4 = true\n")
	sb.WriteString("# return-public-ipv6 = true\n")

	return sb.String()
}
