package config

import (
	"crypto/ed25519"
	"encoding/hex"
	"fmt"
	"net"
	"strings"

	"github.com/yggdrasil-network/yggdrasil-go/src/address"
	ygconfig "github.com/yggdrasil-network/yggdrasil-go/src/config"
)

// Generate returns a freshly generated, single merged ydn64.conf HJSON
// document (new key pair, pre-derived pool6 address) as a string, ready to
// be printed to stdout.
func Generate() (string, error) {
	// Generate a fresh yggdrasil NodeConfig (includes a new random key pair).
	ygCfg := ygconfig.GenerateConfig()

	// Derive node address and pool6 subnet from the generated private key.
	privKey := ed25519.PrivateKey(ygCfg.PrivateKey)
	pubKey := privKey.Public().(ed25519.PublicKey)

	nodeAddr := address.AddrForKey(pubKey) // *address.Address = *[16]byte
	nodeIP := net.IP(nodeAddr[:])

	// address.Subnet is [8]byte — the /64 prefix bytes for this node's subnet.
	subnet := address.SubnetForKey(pubKey) // *address.Subnet = *[8]byte

	// Build the /96 pool6 prefix: 8 subnet bytes + 8 zero bytes → /96 subnet.
	pool6IP := make(net.IP, net.IPv6len) // 16 zero bytes
	copy(pool6IP, subnet[:])             // first 8 bytes from subnet prefix
	pool6CIDR := fmt.Sprintf("%s/96", pool6IP.String())
	pool6Prefix := pool6IP.String() // e.g. "301:363a:9499:c858::"

	privKeyHex := hex.EncodeToString(ygCfg.PrivateKey)

	return buildConf(privKeyHex, nodeIP.String(), pool6CIDR, pool6Prefix), nil
}

func buildConf(privKeyHex, nodeIP, pool6CIDR, pool6Prefix string) string {
	var sb strings.Builder

	sb.WriteString("{\n")
	sb.WriteString("  # ydn64 — TUN-less Yggdrasil node with NAT64 + DNS64\n")
	sb.WriteString("  # Generated by: ydn64 -genconf\n\n")

	sb.WriteString("  # Your private key. DO NOT share this with anyone!\n")
	sb.WriteString(fmt.Sprintf("  PrivateKey: %s\n\n", privKeyHex))

	sb.WriteString("  # List of outbound peer connection strings (e.g. tls://a.b.c.d:e or\n")
	sb.WriteString("  # socks://a.b.c.d:e/f.g.h.i:j). Connection strings can contain options,\n")
	sb.WriteString("  # see https://yggdrasil-network.github.io/configurationref.html#peers.\n")
	sb.WriteString("  # Yggdrasil has no concept of bootstrap nodes - all network traffic\n")
	sb.WriteString("  # will transit peer connections. Therefore make sure to only peer with\n")
	sb.WriteString("  # nearby nodes that have good connectivity and low latency. Avoid adding\n")
	sb.WriteString("  # peers to this list from distant countries as this will worsen your\n")
	sb.WriteString("  # node's connectivity and performance considerably.\n")
	sb.WriteString("  Peers: []\n\n")

	sb.WriteString("  # List of connection strings for outbound peer connections in URI format,\n")
	sb.WriteString("  # arranged by source interface, e.g. { \"eth0\": [ \"tls://a.b.c.d:e\" ] }.\n")
	sb.WriteString("  # You should only use this option if your machine is multi-homed and you\n")
	sb.WriteString("  # want to establish outbound peer connections on different interfaces.\n")
	sb.WriteString("  # Otherwise you should use \"Peers\".\n")
	sb.WriteString("  InterfacePeers: {}\n\n")

	sb.WriteString("  # Listen addresses for incoming connections. You will need to add\n")
	sb.WriteString("  # listeners in order to accept incoming peerings from non-local nodes.\n")
	sb.WriteString("  # This is not required if you wish to establish outbound peerings only.\n")
	sb.WriteString("  # Multicast peer discovery will work regardless of any listeners set\n")
	sb.WriteString("  # here. Each listener should be specified in URI format as above, e.g.\n")
	sb.WriteString("  # tls://0.0.0.0:0 or tls://[::]:0 to listen on all interfaces.\n")
	sb.WriteString("  Listen: []\n\n")

	sb.WriteString("  # Configuration for which interfaces multicast peer discovery should be\n")
	sb.WriteString("  # enabled on. Regex is a regular expression which is matched against an\n")
	sb.WriteString("  # interface name, and interfaces use the first configuration that they\n")
	sb.WriteString("  # match against. Beacon controls whether or not your node advertises its\n")
	sb.WriteString("  # presence to others, whereas Listen controls whether or not your node\n")
	sb.WriteString("  # listens out for and tries to connect to other advertising nodes. See\n")
	sb.WriteString("  # https://yggdrasil-network.github.io/configurationref.html#multicastinterfaces\n")
	sb.WriteString("  # for more supported options.\n")
	sb.WriteString("  MulticastInterfaces: [\n")
	sb.WriteString("    {\n      Regex: .*\n      Beacon: true\n      Listen: true\n      Password: \"\"\n    }\n")
	sb.WriteString("  ]\n\n")

	sb.WriteString("  # List of peer public keys to allow incoming peering connections\n")
	sb.WriteString("  # from. If left empty/undefined then all connections will be allowed\n")
	sb.WriteString("  # by default. This does not affect outgoing peerings, nor does it\n")
	sb.WriteString("  # affect link-local peers discovered via multicast.\n")
	sb.WriteString("  # WARNING: THIS IS NOT A FIREWALL and DOES NOT limit who can reach\n")
	sb.WriteString("  # open ports or services running on your machine!\n")
	sb.WriteString("  AllowedPublicKeys: []\n\n")

	sb.WriteString("  # By default, nodeinfo contains some defaults including the platform,\n")
	sb.WriteString("  # architecture and Yggdrasil version. These can help when surveying\n")
	sb.WriteString("  # the network and diagnosing network routing problems. Enabling\n")
	sb.WriteString("  # nodeinfo privacy prevents this, so that only items specified in\n")
	sb.WriteString("  # \"NodeInfo\" are sent back if specified.\n")
	sb.WriteString("  NodeInfoPrivacy: false\n\n")

	sb.WriteString("  # Optional nodeinfo. This must be a { \"key\": \"value\", ... } map\n")
	sb.WriteString("  # or set as null. This is entirely optional but, if set, is visible\n")
	sb.WriteString("  # to the whole network on request.\n")
	sb.WriteString("  NodeInfo: {}\n\n")

	sb.WriteString("  # Shared allowed source filter for both NAT64 and DNS64 services.\n")
	sb.WriteString("  # CIDR notation or individual IPv6 addresses.\n")
	sb.WriteString("  # AllowedSources: [\"200::/7\"]\n")
	sb.WriteString("  AllowedSources: [\"200:aaaa:bbbb:cccc:dddd:eeee:ffff:1234/128\"]\n\n")

	sb.WriteString("  # Enable NAT64 service. If false, the NAT64 service will not be started.\n")
	sb.WriteString("  Nat64Enable: true\n\n")

	sb.WriteString("  # NAT64 prefix to use for synthesising IPv6 addresses from IPv4 addresses.\n")
	sb.WriteString("  # Pre-generated from the private key. Must be a /96 prefix.\n")
	sb.WriteString(fmt.Sprintf("  Nat64Pool: %q\n\n", pool6CIDR))

	sb.WriteString("  # Idle timeout in seconds before a UDP NAT64 session is expired.\n")
	sb.WriteString("  Nat64UdpTimeout: 30\n\n")

	sb.WriteString("  # Enable DNS64 service. If false, the DNS64 service will not be started.\n")
	sb.WriteString("  Dns64Enable: true\n\n")

	sb.WriteString("  # Listen address for DNS64 service. Must be a valid IPv6 address and port.\n")
	sb.WriteString("  # Pre-generated from the private key.\n")
	sb.WriteString(fmt.Sprintf("  Dns64Listen: %q\n\n", "["+nodeIP+"]:53"))

	sb.WriteString("  Dns64Default: \"8.8.8.8:53\"\n")
	sb.WriteString("  Dns64CacheExpiration: 300\n")
	sb.WriteString("  Dns64CachePurge: 600\n\n")

	sb.WriteString("  # Dns64InvalidAddress: \"ignore\" | \"process\" | \"discard\"\n")
	sb.WriteString("  # What to do with an \"0.0.0.0\" and [::] addresses\n")
	sb.WriteString("  #   \"ignore\"  - treated like a regular address (i.e. 0.0.0.0 return as [prefix::], [::] - drop)\n")
	sb.WriteString("  #               default behavior.\n")
	sb.WriteString("  #   \"process\" - 0.0.0.0 translate to [::]. [::] return \"as-is\"\n")
	sb.WriteString("  #   \"discard\" - discard this address\n")
	sb.WriteString("  Dns64InvalidAddress: \"ignore\"\n\n")

	sb.WriteString("  Dns64Zones: [\n")
	sb.WriteString("    # Default zone: synthesise AAAA records from A records using the NAT64 prefix.\n")
	sb.WriteString("    {\n")
	sb.WriteString("      domains: [\".\"]\n")
	sb.WriteString("      return-public-ipv4: false\n")
	sb.WriteString(fmt.Sprintf("      prefix: %q\n", pool6Prefix))
	sb.WriteString("    }\n")
	sb.WriteString("    # Example: Yggdrasil-native .ygg zone — forward to Alfis DNS, pass through 200::/7 responses.\n")
	sb.WriteString("    # {\n")
	sb.WriteString("    #   domains: [\".ygg\"]\n")
	sb.WriteString("    #   forwarder: \"[308:84:68:55::]:53\"\n")
	sb.WriteString("    # }\n")
	sb.WriteString("    # Example: Pass-through zone — return real IPv4 and IPv6 records unchanged.\n")
	sb.WriteString("    # {\n")
	sb.WriteString("    #   domains: [\"example.com\", \"com.tr\"]\n")
	sb.WriteString("    #   return-public-ipv4: true\n")
	sb.WriteString("    #   return-public-ipv6: true\n")
	sb.WriteString("    # }\n")
	sb.WriteString("  ]\n")
	sb.WriteString("}\n")

	return sb.String()
}
